# Configurações básicas
spring.application.name=notification-service
server.port=3003
spring.config.import=optional:file:./config/secrets.properties
email.sender=felipemelchior112@gmail.com
auth-service.url=http://localhost:3000/auth
